spring.application.name=order-service
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/orders_db
spring.datasource.username=demo
spring.datasource.password=demo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Service URLs
inventory-service.url=http://inventory-service:8081
payment-service.url=http://payment-service:8082
notification-service.url=http://notification-service:8083
