const fs=require('fs'),path=require('path'),cp=require('child_process');
const R=process.env.BCG_REVIEW_OUT||__dirname,S=require('path').resolve(__dirname,'..');
const {ContextGraphEngine,WorkspaceScanner,GitAnalyzer,ContextCache,NodeApiParser,PythonApiParser,GoApiParser}=require(S+'/packages/core/dist');
const {WatsonxRuntime,WatsonxClient}=require(S+'/packages/watsonx/dist');
for(const d of ['evidence','fixtures','caches','logs'])fs.mkdirSync(R+'/'+d,{recursive:true});
const results=[];const save=(n,x)=>fs.writeFileSync(R+'/evidence/'+n+'.json',JSON.stringify(x,null,2));
const ck=(id,name,ok,actual)=>{results.push({id,name,status:ok?'PASS':'FAIL',actual}); console.log(id, ok ? 'PASS' : 'FAIL', name);save('results',results)};
const git=(r,...a)=>cp.execFileSync('git',a,{cwd:r,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();
const commit=(r,m)=>{git(r,'add','.');git(r,'-c','user.name=QA','-c','user.email=qa@localhost','commit','-qm',m)};
function fixture(n,isgit=true){const r=R+'/fixtures/'+n;fs.cpSync(S+'/demo/microservices',r,{recursive:true});if(isgit){git(r,'init','-q','-b','main');commit(r,'baseline')}return r}
const engine=(r,n)=>new ContextGraphEngine({workspaceRoot:r,cacheDir:R+'/caches/'+n});
const svc=(a,n='order-service')=>a.services.find(s=>s.identity.name===n);
function edit(f,a,b){let t=fs.readFileSync(f,'utf8');if(!t.includes(a))throw Error('Missing replacement: '+a);fs.writeFileSync(f,t.replace(a,b))}
const controller=r=>r+'/order-service/src/main/java/com/demo/order/controller/OrderController.java';
const entity=r=>r+'/order-service/src/main/java/com/demo/order/entity/Order.java';
(async()=>{
const root=await new WorkspaceScanner(S).discoverServices();save('root-discovery',root);ck('F01','Root discovers bundled Spring demo',root.filter(s=>s.detectedStack==='spring-boot').length===3,root.map(s=>[s.serviceId,s.detectedStack]));
let r=fixture('commits'),e=engine(r,'commits'),a=await e.analyze();save('demo-cold',a);
ck('DEMO','3 services / 18 APIs / 5 tables / 3 databases',a.services.length===3&&a.services.flatMap(s=>s.apis).length===18&&a.services.flatMap(s=>s.database).length===5&&a.graph.nodes.filter(n=>n.type==='DATABASE').length===3,{services:a.services.length,apis:a.services.flatMap(s=>s.apis).length,tables:a.services.flatMap(s=>s.database).length,dbs:a.graph.nodes.filter(n=>n.type==='DATABASE').length});
ck('GRAPH','2 service dependency edges',a.graph.edges.filter(x=>x.type==='SERVICE_DEPENDS_ON_SERVICE').length===2,a.graph.edges);
let b=await e.analyze();ck('CACHE','Warm engine uses all three caches',b.cacheStats.cached===3,b.cacheStats);
edit(entity(r),'private Integer customerId;','private UUID customerId;');commit(r,'customerId to UUID');
let ch=await e.detectAndAnalyzeChanges('order-service',a.services);ck('F03-before','Impact works before explicit refresh',!!ch&&ch.affectsDatabase,ch);
b=await e.analyze();save('demo-commit',b);ck('F02','Commit refreshes 1 / caches 2',b.cacheStats.refreshed===1&&b.cacheStats.cached===2,b.cacheStats);
ch=await e.detectAndAnalyzeChanges('order-service',b.services);ck('F03-after','Impact works after analysis',!!ch&&ch.affectsDatabase,ch);
let prompts=[],calls={summary:0,api:0};const runtime=new WatsonxRuntime({isConfigured:()=>true,generate:async p=>{prompts.push(p);return 'summary'},generateJson:async p=>{prompts.push(p);return null}});await runtime.analyzeImpact(ch,svc(b),b.services.filter(s=>s.identity.name!=='order-service'));save('impact-prompts',prompts);ck('F13-facts','Impact prompt includes field before/after types',prompts.some(p=>/customer_?id/i.test(p)&&p.includes('UUID')&&/Integer|INTEGER/.test(p)),prompts);
await e.refreshService('order-service');ch=await e.detectAndAnalyzeChanges('order-service',b.services);ck('F03-refresh','Targeted refresh preserves impact baseline',!!ch,ch);
edit(r+'/order-service/src/main/resources/application.properties','orders_db','orders_v2');commit(r,'rename database');b=await e.analyze();ck('F08','DB rename replaces old DB dependency',svc(b).dependencies.some(d=>d.targetService==='orders_v2')&&!svc(b).dependencies.some(d=>d.targetService==='orders_db'),svc(b).dependencies);
git(r,'checkout','-qb','qa-branch');b=await e.analyze();ck('BRANCH','Fingerprint cache reflects new branch at same HEAD',b.services.every(s=>s.identity.branch==='qa-branch'),b.services.map(s=>s.identity.branch));
r=fixture('dirty');e=engine(r,'dirty');a=await e.analyze();let f=controller(r);edit(f,'/orders','/orders-v2');const ga=new GitAnalyzer(r),h1=ga.getDirtyHash();ck('DIRTY-path','Unstaged path matches actual relative file',ga.getDirtyFiles().some(x=>x.path===path.relative(r,f)),ga.getDirtyFiles());b=await e.analyze();ck('DIRTY-first','Unstaged controller edit refreshes API',svc(b).status==='Changed'&&svc(b).apis.some(x=>x.path.startsWith('/orders-v2')),{status:svc(b).status,paths:svc(b).apis.map(x=>x.path)});
edit(f,'/orders-v2','/orders-v3');const h2=ga.getDirtyHash();ck('DIRTY-hash','Second edit of same file changes dirty hash',h1!==h2,{h1,h2});b=await e.analyze();ck('DIRTY-second','Second unstaged edit appears in APIs',svc(b).apis.some(x=>x.path.startsWith('/orders-v3')),{status:svc(b).status,paths:svc(b).apis.map(x=>x.path)});git(r,'add','.');b=await e.analyze();ck('DIRTY-stage','Staged edit is detected',svc(b).apis.some(x=>x.path.startsWith('/orders-v3')),svc(b).status);ch=await e.detectAndAnalyzeChanges('order-service',b.services);ck('DIRTY-impact','Dirty impact available after initial clean baseline',!!ch&&ch.affectsApi,ch);git(r,'reset','--hard','HEAD');b=await e.analyze();ck('DIRTY-restore','Restore returns clean cache',b.cacheStats.cached===3&&!svc(b).apis.some(x=>x.path.includes('-v3')),b.cacheStats);
r=fixture('dto');e=engine(r,'dto');a=await e.analyze();edit(r+'/order-service/src/main/java/com/demo/order/dto/OrderRequest.java','Integer customerId','UUID customerId');commit(r,'DTO change');b=await e.analyze();ch=await e.detectAndAnalyzeChanges('order-service',b.services);ck('F07','Exposed DTO sets affectsApi after analysis',ch?.affectsApi,ch);
r=fixture('nongit',false);e=engine(r,'nongit');a=await e.analyze();edit(entity(r),'private Integer customerId;','private UUID customerId;');b=await e.analyze();ck('F10-engine','Non-git engine updates source',svc(b).database.some(t=>t.columns.some(c=>c.javaType==='UUID'&&c.name==='customer_id')),b.cacheStats);
const c1=new ContextCache(R+'/caches/shared'),c2=new ContextCache(R+'/caches/shared');c1.set(svc(a));ck('F11-sequential','Second cache instance sees first writer',c2.getLastAnalyzedCommit('order-service')===svc(a).identity.commitHash,c2.getLastAnalyzedCommit('order-service'));const ix=R+'/caches/shared/index.json';let index=JSON.parse(fs.readFileSync(ix));index.metadata['order-service'].schemaVersion=0;fs.writeFileSync(ix,JSON.stringify(index));ck('CACHE-schema','Old schema entries invalidated',new ContextCache(R+'/caches/shared').get('order-service','main','unknown')===null,'schemaVersion=0');
e=engine(S+'/demo','spy');e.setWatsonxClient({generateServiceSummary:async()=>{calls.summary++;return 'spy'},describeApi:async()=>{calls.api++;return 'description'}});await e.analyze();ck('F13-api','describeApi called for all 18 endpoints',calls.api===18,calls);
if(process.env.BCG_DEMO_ROOT){let ms=await engine(process.env.BCG_DEMO_ROOT,'polyglot').analyze();save('polyglot',ms);ck('POLYGLOT','12 application services discovered',ms.services.length===12,ms.services.map(s=>({name:s.identity.name,stack:s.detectedStack,apis:s.apis.length})));}
for(const [stack,manifest,file,code,Parser] of [['node','package.json','routes/api.js',"const express=require('express');\nconst router=express.Router();\nrouter.get('/old', (req,res)=>{});",NodeApiParser],['python','requirements.txt','api.py','from fastapi import FastAPI\napp=FastAPI()\n@app.get("/old")\ndef old():\n return {}\n',PythonApiParser],['go','go.mod','handler.go','package main\nimport "github.com/gin-gonic/gin"\nfunc main() { r := gin.Default(); r.GET("/old", handler) }',GoApiParser]]){
const q=R+'/fixtures/'+stack;fs.mkdirSync(path.dirname(q+'/'+file),{recursive:true});fs.writeFileSync(q+'/'+manifest,stack==='node'?'{}':'');fs.writeFileSync(q+'/'+file,code);git(q,'init','-q','-b','main');commit(q,'baseline');const en=engine(q,stack);let x=await en.analyze();edit(q+'/'+file,'/old','/new');commit(q,'route rename');let y=await en.analyze();ck('POLY-'+stack,'Committed '+stack+' route refreshes',y.services[0].apis.some(a=>a.path==='/new'),{before:x.services[0].apis,after:y.services[0].apis});}
const scanner=new WorkspaceScanner(R+'/fixtures');ck('F09-collision','Canonical IDs resist path flattening collision',scanner.generateServiceId(R+'/fixtures/team-a/order-service')!==scanner.generateServiceId(R+'/fixtures/team/a-order-service'),[scanner.generateServiceId(R+'/fixtures/team-a/order-service'),scanner.generateServiceId(R+'/fixtures/team/a-order-service')]);
const bench=[];for(let i=0;i<5;i++){let en=engine(R+'/fixtures/dto','bench'+i),t=performance.now();await en.analyze();let cold=performance.now()-t;t=performance.now();await en.analyze();bench.push({coldMs:cold,warmMs:performance.now()-t})}save('benchmarks',bench);
console.log('SUMMARY',results.filter(x=>x.status==='PASS').length,'PASS',results.filter(x=>x.status==='FAIL').length,'FAIL');
})().catch(e=>{console.error(e);save('results',results);process.exitCode=1});
