spring.application.name=payment-service
server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/payment_db
spring.datasource.username=demo
spring.datasource.password=demo
spring.jpa.hibernate.ddl-auto=update
